
pull_request_rules:
  - name: Automated merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - status-success=build
      - status-success=unit-tests
      - status-success=lint
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge
      label:
        add: ["chore(deps):","🛠 Improvement"]
